# Drone config file for a basic npm application
#
# VERSION: 1.0.0

kind: pipeline
type: docker
name: test

steps:
  - name: restore cache
    image: registry.qonvextechnology.com:5000/drillster/drone-volume-cache:latest
    settings:
      restore: true
      cache_key:
        - DRONE_STAGE_NAME
        - DRONE_REPO_OWNER
        - DRONE_REPO_NAME
        - DRONE_REPO_BRANCH
      mount:
        - "node_modules"
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: registry.qonvextechnology.com:5000/node-yarn:latest
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn

    commands:
      - yarn --mutex file:/usr/local/share/.cache/yarn/.yarn-mutex

  - name: rebuild cache
    image: registry.qonvextechnology.com:5000/drillster/drone-volume-cache:latest
    settings:
      rebuild: true
      cache_key:
        - DRONE_STAGE_NAME
        - DRONE_REPO_OWNER
        - DRONE_REPO_NAME
        - DRONE_REPO_BRANCH
      mount:
        - "node_modules"
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: yarn
    host:
      path: /tmp/yarn
  - name: cache
    host:
      path: /tmp/drone-cache

---
kind: pipeline
type: docker
name: deploy-master

trigger:
  branch:
    - master
    - feature/drone-ci

steps:
  - name: restore cache
    image: registry.qonvextechnology.com:5000/drillster/drone-volume-cache:latest
    settings:
      restore: true
      cache_key:
        - DRONE_STAGE_NAME
        - DRONE_REPO_OWNER
        - DRONE_REPO_NAME
        - DRONE_REPO_BRANCH
      mount:
        - "node_modules"
        - "dist"
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: registry.qonvextechnology.com:5000/node-yarn:latest
    volumes:
      - name: yarn
        path: /usr/local/share/.cache/yarn

    commands:
      - yarn --mutex file:/usr/local/share/.cache/yarn/.yarn-mutex
      - yarn build

  - name: rebuild cache
    image: registry.qonvextechnology.com:5000/drillster/drone-volume-cache:latest
    settings:
      rebuild: true
      cache_key:
        - DRONE_STAGE_NAME
        - DRONE_REPO_OWNER
        - DRONE_REPO_NAME
        - DRONE_REPO_BRANCH
      mount:
        - "node_modules"
        - "dist"
    volumes:
      - name: cache
        path: /cache

  - name: build image
    image: registry.qonvextechnology.com:5000/plugins/docker
    privileged: true
    settings:
      repo: registry.qonvextechnology.com:5000/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}
      tags: master
      cache_from:
        - "registry.qonvextechnology.com:5000/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}:master"

volumes:
  - name: yarn
    host:
      path: /tmp/yarn
  - name: cache
    host:
      path: /tmp/drone-cache

depends_on:
  - test
